/// <reference types='./globals.d.ts' />
/* tslint:disable */
 
/**
 * 默认模块 - version 1.0.0
 *
 *
 *
 * OpenAPI version: 3.1.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'service.update': ['PUT', '/service'],
  'service.create': ['POST', '/service'],
  'service.get': ['GET', '/service/{id}'],
  'service.delete_': ['DELETE', '/service/{id}'],
  'service.list': ['GET', '/service/list'],
  'asset.update_1': ['PUT', '/server'],
  'asset.create_1': ['POST', '/server'],
  'asset.get_1': ['GET', '/server/{id}'],
  'asset.delete_1': ['DELETE', '/server/{id}'],
  'asset.list_1': ['GET', '/server/list'],
  'serviceControl.executeControl': ['POST', '/control/execute'],
  'serviceControl.getStatus': ['GET', '/control/status'],
  'monitor.getOverview': ['GET', '/monitor/overview'],
  'monitor.getNetworkUsage': ['GET', '/monitor/network'],
  'monitor.getMemoryUsage': ['GET', '/monitor/memory'],
  'monitor.getDiskUsage': ['GET', '/monitor/disk'],
  'monitor.getCpuUsage': ['GET', '/monitor/cpu']
};
