/* tslint:disable */
/* eslint-disable */
/**
 * 默认模块 - version 1.0.0
 *
 *
 *
 * OpenAPI version: 3.1.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from './index';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

export interface ServiceInfoUpdateBo {
  /**
   * 主键ID
   */
  id: string;
  /**
   * 服务名称
   */
  serviceName?: string;
  /**
   * 服务类型
   */
  serviceType?: 'docker' | 'systemctl' | 'custom';
  /**
   * 服务描述
   */
  description?: string;
  /**
   * 自定义启动命令(仅custom类型使用)
   */
  startCommand?: string;
  /**
   * 自定义停止命令(仅custom类型使用)
   */
  stopCommand?: string;
  /**
   * 自定义重启命令(仅custom类型使用)
   */
  restartCommand?: string;
  /**
   * 自定义查看状态命令(仅custom类型使用)
   */
  statusCommand?: string;
}
export interface ServiceInfoAddBo {
  /**
   * 关联的服务器主键ID
   */
  serverId: string;
  /**
   * 服务名称
   */
  serviceName: string;
  /**
   * 服务类型
   */
  serviceType: 'docker' | 'systemctl' | 'custom';
  /**
   * 服务描述
   */
  description?: string;
  /**
   * 自定义启动命令(仅custom类型使用)
   */
  startCommand?: string;
  /**
   * 自定义停止命令(仅custom类型使用)
   */
  stopCommand?: string;
  /**
   * 自定义重启命令(仅custom类型使用)
   */
  restartCommand?: string;
  /**
   * 自定义查看状态命令(仅custom类型使用)
   */
  statusCommand?: string;
}
export interface ServerAssetUpdateBo {
  /**
   * 主键ID
   */
  id: string;
  /**
   * 主机别名
   */
  hostName?: string;
  /**
   * SSH端口，有效范围 1-65535
   */
  sshPort?: number;
  /**
   * SSH登录用户名
   */
  sshUsername?: string;
  /**
   * SSH登录密码
   */
  sshPassword?: string;
  /**
   * Node Exporter 指标采集端口，有效范围 1-65535
   */
  nodeExporterPort?: number;
}
export interface ServerAssetAddBo {
  /**
   * 服务器IP地址
   */
  hostIp: string;
  /**
   * 主机别名
   */
  hostName: string;
  /**
   * SSH端口，有效范围 1-65535
   */
  sshPort: number;
  /**
   * SSH登录用户名
   */
  sshUsername: string;
  /**
   * SSH登录密码
   */
  sshPassword: string;
  /**
   * Node Exporter 指标采集端口，有效范围 1-65535
   */
  nodeExporterPort: number;
}
export interface ControlExecuteBo {
  /**
   * 服务ID
   */
  serviceId: string;
  /**
   * 操作类型
   */
  action: 'start' | 'stop' | 'restart';
}
export interface ServerOverview {
  /**
   * 服务器主键ID
   */
  serverId: string;
  /**
   * 服务器主机名称
   */
  hostName: string;
  /**
   * CPU 使用率 (%)
   */
  cpuUsage: string;
  /**
   * 内存 使用率 (%)
   */
  memoryUsage: string;
  /**
   * 磁盘 使用率 (%)
   */
  diskUsage: string;
}
export interface RListServerOverview {
  /**
   * 消息状态码
   */
  code?: number;
  /**
   * 消息内容
   */
  msg?: string;
  /**
   * 数据对象
   */
  data?: ServerOverview[];
}
export interface ServiceInfoVo {
  /**
   * 主键ID
   */
  id: string;
  /**
   * 关联的服务器主键ID
   */
  serverId: string;
  /**
   * 服务名称
   */
  serviceName: string;
  /**
   * 服务类型
   */
  serviceType: 'docker' | 'systemctl' | 'custom';
  /**
   * 服务描述
   */
  description: string;
  /**
   * 自定义启动命令
   */
  startCommand?: string;
  /**
   * 自定义停止命令
   */
  stopCommand?: string;
  /**
   * 自定义重启命令
   */
  restartCommand?: string;
  /**
   * 自定义查看状态命令
   */
  statusCommand?: string;
}
export interface RListServiceInfoVo {
  /**
   * 消息状态码
   */
  code?: number;
  /**
   * 消息内容
   */
  msg?: string;
  /**
   * 数据对象
   */
  data?: ServiceInfoVo[];
}
export interface RBoolean {
  /**
   * 消息状态码
   */
  code?: number;
  /**
   * 消息内容
   */
  msg?: string;
  /**
   * 数据对象
   */
  data?: boolean;
}
export interface RLong {
  /**
   * 消息状态码
   */
  code?: number;
  /**
   * 消息内容
   */
  msg?: string;
  /**
   * 数据对象
   */
  data?: number;
}
export interface RServiceInfoVo {
  /**
   * 消息状态码
   */
  code?: number;
  /**
   * 消息内容
   */
  msg?: string;
  /**
   * 数据对象
   */
  data?: ServiceInfoVo;
}
export interface ServerAssetVo {
  /**
   * 主键ID
   */
  id: string;
  /**
   * 服务器IP地址
   */
  hostIp: string;
  /**
   * 主机别名
   */
  hostName: string;
  /**
   * SSH端口
   */
  sshPort: number;
  /**
   * SSH登录用户名
   */
  sshUsername: string;
  /**
   * Node Exporter 指标采集端口
   */
  nodeExporterPort: number;
}
export interface RListServerAssetVo {
  /**
   * 消息状态码
   */
  code?: number;
  /**
   * 消息内容
   */
  msg?: string;
  /**
   * 数据对象
   */
  data?: ServerAssetVo[];
}
export interface RServerAssetVo {
  /**
   * 消息状态码
   */
  code?: number;
  /**
   * 消息内容
   */
  msg?: string;
  /**
   * 数据对象
   */
  data?: ServerAssetVo;
}
export interface RString {
  /**
   * 消息状态码
   */
  code?: number;
  /**
   * 消息内容
   */
  msg?: string;
  /**
   * 数据对象
   */
  data?: string;
}
export interface RInteger {
  /**
   * 消息状态码
   */
  code?: number;
  /**
   * 消息内容
   */
  msg?: string;
  /**
   * 数据对象
   */
  data?: number;
}
export interface MetricPoint {
  /**
   * 13位毫秒时间戳
   */
  timestamp?: number;
  /**
   * 指标值
   */
  value?: number;
}
export interface RListMetricPoint {
  /**
   * 消息状态码
   */
  code?: number;
  /**
   * 消息内容
   */
  msg?: string;
  /**
   * 数据对象
   */
  data?: MetricPoint[];
}
export interface NetworkUsageVo {
  /**
   * 接收速率（bps）
   */
  rx: MetricPoint[];
  /**
   * 发送速率（bps）
   */
  tx: MetricPoint[];
}
export interface RNetworkUsageVo {
  /**
   * 消息状态码
   */
  code?: number;
  /**
   * 消息内容
   */
  msg?: string;
  /**
   * 数据对象
   */
  data?: NetworkUsageVo;
}
declare global {
  interface Apis {
    service: {
      /**
       * ---
       *
       * [GET] 获取服务列表（支持多条件查询）
       *
       * **path:** /api/service/list
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 关联的服务器主键ID
       *   serverId?: string
       *   // 服务名称（模糊匹配）
       *   serviceName?: string
       *   // 服务类型
       *   serviceType?: 'docker' | 'systemctl' | 'custom'
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 消息状态码
       *   code?: number
       *   // 消息内容
       *   msg?: string
       *   // 数据对象
       *   // [items] start
       *   // 服务信息列表展示
       *   // [items] end
       *   data?: Array<{
       *     // 主键ID
       *     id: string
       *     // 关联的服务器主键ID
       *     serverId: string
       *     // 服务名称
       *     serviceName: string
       *     // 服务类型
       *     serviceType: 'docker' | 'systemctl' | 'custom'
       *     // 服务描述
       *     description: string
       *     // 自定义启动命令
       *     startCommand?: string
       *     // 自定义停止命令
       *     stopCommand?: string
       *     // 自定义重启命令
       *     restartCommand?: string
       *     // 自定义查看状态命令
       *     statusCommand?: string
       *   }>
       * }
       * ```
       */
      list<
        Config extends Alova2MethodConfig<RListServiceInfoVo> & {
          params: {
            /**
             * 关联的服务器主键ID
             */
            serverId?: string;
            /**
             * 服务名称（模糊匹配）
             */
            serviceName?: string;
            /**
             * 服务类型
             */
            serviceType?: 'docker' | 'systemctl' | 'custom';
          };
        }
      >(
        config: Config
      ): Alova2Method<RListServiceInfoVo, 'service.list', Config>;
      /**
       * ---
       *
       * [PUT] 编辑服务
       *
       * **path:** /api/service
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 主键ID
       *   id: string
       *   // 服务名称
       *   serviceName?: string
       *   // 服务类型
       *   serviceType?: 'docker' | 'systemctl' | 'custom'
       *   // 服务描述
       *   description?: string
       *   // 自定义启动命令(仅custom类型使用)
       *   startCommand?: string
       *   // 自定义停止命令(仅custom类型使用)
       *   stopCommand?: string
       *   // 自定义重启命令(仅custom类型使用)
       *   restartCommand?: string
       *   // 自定义查看状态命令(仅custom类型使用)
       *   statusCommand?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 消息状态码
       *   code?: number
       *   // 消息内容
       *   msg?: string
       *   // 数据对象
       *   data?: boolean
       * }
       * ```
       */
      update<
        Config extends Alova2MethodConfig<RBoolean> & {
          data: ServiceInfoUpdateBo;
        }
      >(
        config: Config
      ): Alova2Method<RBoolean, 'service.update', Config>;
      /**
       * ---
       *
       * [POST] 新增服务
       *
       * **path:** /api/service
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 关联的服务器主键ID
       *   serverId: string
       *   // 服务名称
       *   serviceName: string
       *   // 服务类型
       *   serviceType: 'docker' | 'systemctl' | 'custom'
       *   // 服务描述
       *   description?: string
       *   // 自定义启动命令(仅custom类型使用)
       *   startCommand?: string
       *   // 自定义停止命令(仅custom类型使用)
       *   stopCommand?: string
       *   // 自定义重启命令(仅custom类型使用)
       *   restartCommand?: string
       *   // 自定义查看状态命令(仅custom类型使用)
       *   statusCommand?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 消息状态码
       *   code?: number
       *   // 消息内容
       *   msg?: string
       *   // 数据对象
       *   data?: number
       * }
       * ```
       */
      create<
        Config extends Alova2MethodConfig<RLong> & {
          data: ServiceInfoAddBo;
        }
      >(
        config: Config
      ): Alova2Method<RLong, 'service.create', Config>;
      /**
       * ---
       *
       * [GET] 根据ID获取服务详情
       *
       * **path:** /api/service/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 消息状态码
       *   code?: number
       *   // 消息内容
       *   msg?: string
       *   // 数据对象
       *   data?: {
       *     // 主键ID
       *     id: string
       *     // 关联的服务器主键ID
       *     serverId: string
       *     // 服务名称
       *     serviceName: string
       *     // 服务类型
       *     serviceType: 'docker' | 'systemctl' | 'custom'
       *     // 服务描述
       *     description: string
       *     // 自定义启动命令
       *     startCommand?: string
       *     // 自定义停止命令
       *     stopCommand?: string
       *     // 自定义重启命令
       *     restartCommand?: string
       *     // 自定义查看状态命令
       *     statusCommand?: string
       *   }
       * }
       * ```
       */
      get<
        Config extends Alova2MethodConfig<RServiceInfoVo> & {
          pathParams: {
            id: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<RServiceInfoVo, 'service.get', Config>;
      /**
       * ---
       *
       * [DELETE] 删除服务
       *
       * **path:** /api/service/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 消息状态码
       *   code?: number
       *   // 消息内容
       *   msg?: string
       *   // 数据对象
       *   data?: boolean
       * }
       * ```
       */
      delete_<
        Config extends Alova2MethodConfig<RBoolean> & {
          pathParams: {
            id: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<RBoolean, 'service.delete_', Config>;
    };
    asset: {
      /**
       * ---
       *
       * [GET] 获取服务器列表（支持多条件查询）
       *
       * **path:** /api/server/list
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 服务器IP地址（模糊匹配）
       *   hostIp?: string
       *   // 主机别名（模糊匹配）
       *   hostName?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 消息状态码
       *   code?: number
       *   // 消息内容
       *   msg?: string
       *   // 数据对象
       *   // [items] start
       *   // 服务器资产列表展示
       *   // [items] end
       *   data?: Array<{
       *     // 主键ID
       *     id: string
       *     // 服务器IP地址
       *     hostIp: string
       *     // 主机别名
       *     hostName: string
       *     // SSH端口
       *     sshPort: number
       *     // SSH登录用户名
       *     sshUsername: string
       *     // Node Exporter 指标采集端口
       *     nodeExporterPort: number
       *   }>
       * }
       * ```
       */
      list_1<
        Config extends Alova2MethodConfig<RListServerAssetVo> & {
          params: {
            /**
             * 服务器IP地址（模糊匹配）
             */
            hostIp?: string;
            /**
             * 主机别名（模糊匹配）
             */
            hostName?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<RListServerAssetVo, 'asset.list_1', Config>;
      /**
       * ---
       *
       * [PUT] 编辑服务器
       *
       * **path:** /api/server
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 主键ID
       *   id: string
       *   // 主机别名
       *   hostName?: string
       *   // SSH端口，有效范围 1-65535
       *   sshPort?: number
       *   // SSH登录用户名
       *   sshUsername?: string
       *   // SSH登录密码
       *   sshPassword?: string
       *   // Node Exporter 指标采集端口，有效范围 1-65535
       *   nodeExporterPort?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 消息状态码
       *   code?: number
       *   // 消息内容
       *   msg?: string
       *   // 数据对象
       *   data?: boolean
       * }
       * ```
       */
      update_1<
        Config extends Alova2MethodConfig<RBoolean> & {
          data: ServerAssetUpdateBo;
        }
      >(
        config: Config
      ): Alova2Method<RBoolean, 'asset.update_1', Config>;
      /**
       * ---
       *
       * [POST] 新增服务器
       *
       * **path:** /api/server
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 服务器IP地址
       *   hostIp: string
       *   // 主机别名
       *   hostName: string
       *   // SSH端口，有效范围 1-65535
       *   sshPort: number
       *   // SSH登录用户名
       *   sshUsername: string
       *   // SSH登录密码
       *   sshPassword: string
       *   // Node Exporter 指标采集端口，有效范围 1-65535
       *   nodeExporterPort: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 消息状态码
       *   code?: number
       *   // 消息内容
       *   msg?: string
       *   // 数据对象
       *   data?: number
       * }
       * ```
       */
      create_1<
        Config extends Alova2MethodConfig<RLong> & {
          data: ServerAssetAddBo;
        }
      >(
        config: Config
      ): Alova2Method<RLong, 'asset.create_1', Config>;
      /**
       * ---
       *
       * [GET] 根据ID获取服务器详情
       *
       * **path:** /api/server/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // 服务器主键ID
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 消息状态码
       *   code?: number
       *   // 消息内容
       *   msg?: string
       *   // 数据对象
       *   data?: {
       *     // 主键ID
       *     id: string
       *     // 服务器IP地址
       *     hostIp: string
       *     // 主机别名
       *     hostName: string
       *     // SSH端口
       *     sshPort: number
       *     // SSH登录用户名
       *     sshUsername: string
       *     // Node Exporter 指标采集端口
       *     nodeExporterPort: number
       *   }
       * }
       * ```
       */
      get_1<
        Config extends Alova2MethodConfig<RServerAssetVo> & {
          pathParams: {
            /**
             * 服务器主键ID
             */
            id: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<RServerAssetVo, 'asset.get_1', Config>;
      /**
       * ---
       *
       * [DELETE] 删除服务器
       *
       * **path:** /api/server/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // 服务器主键ID
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 消息状态码
       *   code?: number
       *   // 消息内容
       *   msg?: string
       *   // 数据对象
       *   data?: boolean
       * }
       * ```
       */
      delete_1<
        Config extends Alova2MethodConfig<RBoolean> & {
          pathParams: {
            /**
             * 服务器主键ID
             */
            id: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<RBoolean, 'asset.delete_1', Config>;
    };
    serviceControl: {
      /**
       * ---
       *
       * [POST] 执行服务管控命令
       *
       * **path:** /api/control/execute
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 服务ID
       *   serviceId: string
       *   // 操作类型
       *   action: 'start' | 'stop' | 'restart'
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 消息状态码
       *   code?: number
       *   // 消息内容
       *   msg?: string
       *   // 数据对象
       *   data?: string
       * }
       * ```
       */
      executeControl<
        Config extends Alova2MethodConfig<RString> & {
          data: ControlExecuteBo;
        }
      >(
        config: Config
      ): Alova2Method<RString, 'serviceControl.executeControl', Config>;
      /**
       * ---
       *
       * [GET] 查询服务运行状态
       *
       * **path:** /api/control/status
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 服务ID
       *   serviceId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 消息状态码
       *   code?: number
       *   // 消息内容
       *   msg?: string
       *   // 数据对象
       *   data?: number
       * }
       * ```
       */
      getStatus<
        Config extends Alova2MethodConfig<RInteger> & {
          params: {
            /**
             * 服务ID
             */
            serviceId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<RInteger, 'serviceControl.getStatus', Config>;
    };
    monitor: {
      /**
       * ---
       *
       * [GET] 获取所有服务器监控总览
       *
       * **path:** /api/monitor/overview
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 消息状态码
       *   code?: number
       *   // 消息内容
       *   msg?: string
       *   // 数据对象
       *   // [items] start
       *   // 服务器监控总览数据
       *   // [items] end
       *   data?: Array<{
       *     // 服务器主键ID
       *     serverId: string
       *     // 服务器主机名称
       *     hostName: string
       *     // CPU 使用率 (%)
       *     cpuUsage: string
       *     // 内存 使用率 (%)
       *     memoryUsage: string
       *     // 磁盘 使用率 (%)
       *     diskUsage: string
       *   }>
       * }
       * ```
       */
      getOverview<Config extends Alova2MethodConfig<RListServerOverview>>(
        config?: Config
      ): Alova2Method<RListServerOverview, 'monitor.getOverview', Config>;
      /**
       * ---
       *
       * [GET] 获取内存使用率趋势
       *
       * **path:** /api/monitor/memory
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 服务器主键ID
       *   serverId?: string
       *   // 查询时间范围（秒），默认 3600
       *   duration?: number
       *   // 采样步长（秒），默认 60
       *   step?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 消息状态码
       *   code?: number
       *   // 消息内容
       *   msg?: string
       *   // 数据对象
       *   // [items] start
       *   // 监控指标数据点
       *   // [items] end
       *   data?: Array<{
       *     // 13位毫秒时间戳
       *     timestamp?: number
       *     // 指标值
       *     value?: number
       *   }>
       * }
       * ```
       */
      getMemoryUsage<
        Config extends Alova2MethodConfig<RListMetricPoint> & {
          params: {
            /**
             * 服务器主键ID
             */
            serverId?: string;
            /**
             * 查询时间范围（秒），默认 3600
             */
            duration?: number;
            /**
             * 采样步长（秒），默认 60
             */
            step?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<RListMetricPoint, 'monitor.getMemoryUsage', Config>;
      /**
       * ---
       *
       * [GET] 获取磁盘使用率趋势
       *
       * **path:** /api/monitor/disk
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 服务器主键ID
       *   serverId?: string
       *   // 查询时间范围（秒），默认 3600
       *   duration?: number
       *   // 采样步长（秒），默认 60
       *   step?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 消息状态码
       *   code?: number
       *   // 消息内容
       *   msg?: string
       *   // 数据对象
       *   // [items] start
       *   // 监控指标数据点
       *   // [items] end
       *   data?: Array<{
       *     // 13位毫秒时间戳
       *     timestamp?: number
       *     // 指标值
       *     value?: number
       *   }>
       * }
       * ```
       */
      getDiskUsage<
        Config extends Alova2MethodConfig<RListMetricPoint> & {
          params: {
            /**
             * 服务器主键ID
             */
            serverId?: string;
            /**
             * 查询时间范围（秒），默认 3600
             */
            duration?: number;
            /**
             * 采样步长（秒），默认 60
             */
            step?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<RListMetricPoint, 'monitor.getDiskUsage', Config>;
      /**
       * ---
       *
       * [GET] 获取 CPU 使用率趋势
       *
       * **path:** /api/monitor/cpu
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 服务器主键ID
       *   serverId?: string
       *   // 查询时间范围（秒），默认 3600
       *   duration?: number
       *   // 采样步长（秒），默认 60
       *   step?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 消息状态码
       *   code?: number
       *   // 消息内容
       *   msg?: string
       *   // 数据对象
       *   // [items] start
       *   // 监控指标数据点
       *   // [items] end
       *   data?: Array<{
       *     // 13位毫秒时间戳
       *     timestamp?: number
       *     // 指标值
       *     value?: number
       *   }>
       * }
       * ```
       */
      getCpuUsage<
        Config extends Alova2MethodConfig<RListMetricPoint> & {
          params: {
            /**
             * 服务器主键ID
             */
            serverId?: string;
            /**
             * 查询时间范围（秒），默认 3600
             */
            duration?: number;
            /**
             * 采样步长（秒），默认 60
             */
            step?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<RListMetricPoint, 'monitor.getCpuUsage', Config>;
      /**
       * ---
       *
       * [GET] 获取网络流量趋势
       *
       * **path:** /api/monitor/network
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 服务器主键ID
       *   serverId?: string
       *   // 查询时间范围（秒），默认 3600
       *   duration?: number
       *   // 采样步长（秒），默认 60
       *   step?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 消息状态码
       *   code?: number
       *   // 消息内容
       *   msg?: string
       *   // 数据对象
       *   data?: {
       *     // 接收速率（bps）
       *     // [items] start
       *     // 监控指标数据点
       *     // [items] end
       *     rx: Array<{
       *       // 13位毫秒时间戳
       *       timestamp?: number
       *       // 指标值
       *       value?: number
       *     }>
       *     // 发送速率（bps）
       *     // [items] start
       *     // 监控指标数据点
       *     // [items] end
       *     tx: Array<{
       *       // 13位毫秒时间戳
       *       timestamp?: number
       *       // 指标值
       *       value?: number
       *     }>
       *   }
       * }
       * ```
       */
      getNetworkUsage<
        Config extends Alova2MethodConfig<RNetworkUsageVo> & {
          params: {
            /**
             * 服务器主键ID
             */
            serverId?: string;
            /**
             * 查询时间范围（秒），默认 3600
             */
            duration?: number;
            /**
             * 采样步长（秒），默认 60
             */
            step?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<RNetworkUsageVo, 'monitor.getNetworkUsage', Config>;
    };
  }

  var Apis: Apis;
}
